---
title: "Inferência Estatística - Estimação"
author: "Felipe Albuquerque"
date: "10 de junho de 2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Estimação por ponto e intervalar

## Estimativa por Ponto
Único número que é a melhor avaliação do parâmetro

Eles devem ser:

 (1) Está centrada em torno do parâmetro <- não tendencioso
 
 (2) Tem um erro padrão tão pequeno quanto possível <- eficiente
 
Mais comuns: **Média, mediana, proporção**

 "^" representa estimativa. Â, por exemplo, é uma estimativa de A.

-Método de estimação de máxima verossimilhança
Valor do parâmetro que é mais consistente com os dados observados:

(1) Elas são eficientes para amostras relativamente grandes: outros estimadores não têm erros padrão menores e não tendem a estar próximos do parâmetro

(2) Eles têm pouca, ou nenhuma, tendenciosidade, com a tendenciosidade diminuindo à medida que o tamanho da amostra aumenta

(3) Eles têm distribuições aproximadamente normais

## Estimativa intervalar
Conjunto de números em torno da estimativa por ponto dentro do qual o valor do parâmetro deve estar.

A informação sobre a precisão de uma estimativa por ponto determina a amplitude de uma *estimativa intervalar* para o parâmetro, que consiste em um intervalo de valores em torno da estimativa por ponto. <- intervalo de confiança.

**Intervalo de confiança** para um parâmetro é um intervalo de números que, se acredita, contrnha o parâmetro com determinada probabilidade. A probabilidade de que o intervalo construído em torno da estimativa pontual contenha o parâmtro é denominada de nível de confiança. Ele é um número escolhido e está próximo a 1, 0.99 ou 0.95

Um intervalo de confiança tem a fórmula: **estimativa por ponto + ou - margem de erro**.

# Intervalo de confiança para uma proporção

Para resumir dados categóricos, registramos as *proporções* (ou percentuais) das observações nas categorias.

## A proporção amostral e seu erro padrão

A medida que o tamanho da amostra aumenta, o erro padrão fica menor. A proporção amostral, então, tende a estar mais próxima da proporção populacional.

$$\sigma_{\pi e} = \frac{\sigma}{\sqrt{n}} = \frac{\sqrt{\pi(1 - \pi)}}{n}$$

## Intervalo de confiança para uma proporção com grandes amostras

Visto qu uma proporção amostral $\pi e$  é uma média amostral, o Teorema Central do Limite se aplica: para amostras aleatórias grandes, a distribuição amostral de $\pi e$ é aproximadamente normal em relação ao parâmetro $\pi$ que ele estima. Nesse caso, substituimos o parâmetro pela proporção amostral, logo:

$$erro padrão = \frac{\sqrt{\pi e(1 - \pi e)}}{n}$$

## Controlando o intervalo de confiança

Com um intervalo de 0.95 de confiança, ou *95% de confiança*, temos
$\pi e $\pm$  1.96$.

Se quisermos 99% de confiança, fica $\pi e $\pm$  2.58$

Vê-se que aumentou o desvio padrão em relação à média. Logo, fica menos precisa a estimação.

## Tamanhos de amostras maiores dão intervalos menores

A amplitude de um intervalo de confiança **aumenta** à medida que o nível de confiança aumenta e **diminui** à medida que o tamanho da amostra diminui.

## Probabilidade de erro

A probabilidade de que um método de estimação de um intervalo gere um intervalo de confiança que não contenha o parâmetro é chamado de **intervalo de erro**. Isso é igual a 1 menos o intervalo de confiança, ou $1 - \alpha$. O de 95%, por exemplo, é $1 - 0.95 = 0.05$.

## Nível de confiança é a proporção correta a longo prazo*

* Por longo prazo entende-se após um grande número de repetições. Ou seja, descreve como é o desempenho do método quando usado repetidamente com várias amostras aleatórias diferentes. Por exemplo, se trabalhamos com um nível de confiança de 95%, esperamos que, repetindo 100 vezes com amostras aleatórias, esperamos que em 95 delas contenham $\pi$.

# Intervalo de confiança para uma média

## Erro padrão estimado para a margem de erro.

Como um intervalo de confiança para uma proporção, o interalo de confiança para uma média tem a forma **estimativa por ponto $\pm$ margem de erro**.

Assim como para categorias, os intervalos de confiança usam o erro padrão estimado:

$$ ep = s/\sqrt{n}$$

## A distribuição t

O escore-t é como o escore-z, mas ele vem de uma distribuição com a forma de sino um pouco mais dispersa do que a distribuição normal.

(1) A distribuição *t* tem a forma de sino e é simétrica em relação à média de 0

(2) O desvio padrão é um pouco maior que 1. O valor preciso depende do que é chamado de **graus de liberdade**, representado por *gl*. A distribuição *t* tem uma dispersão levemente diferente para cada valor distinto do *gl*, e escores-*t* se aplicam para cada valor do *gl*.

(3) Para as inferências da média populacional, os graus de liberdade são iguais a $gl = n - 1$, um a menos do que o tamanho da amostra utilizada.

(4) A distribuição *t* tem caudas mais grossas e é mais dispersa do que a distribuição normal padrão. Quando *gl* é aproximadamente 30 ou mais, as duas distribuições são quase idênticas.

(5) Um escore-*t* multiplicado pelo erro padrão estimado dá a margem de erro para um intervalo de confiança para a média.

Os intervalos de confiança para uma média se parecem com aqueles para as proporções, exceto que eles usam a distribuição *t* em vez da normal.

O intervalo de confiança usa o escore-*t* com uma probabilidade em cada cauda de $\alpha/2$. Ou seja, com um intervalo de confiança de 99%, temos $\alpha = \frac{1 - 0.99}{2} = 0.005$.

Um método estatístico é dito ser robusto quando ele tem um desempenho adequado mesmo quando aquela suposição for violada. <-- suposição de normalidade, por exemplo.

# Escolha o tamanho da amostra

- A *margem de erro* depende diretamente do *erro padrão* para a distribuição amostral da estimativa por ponto

- O *erro padrão* depende, ele próprio, do *tamanho da amostra*.

Para determinar o tamanho da amostra, devemos decidir sobre a margem de erro desejada.

## Fórmula do tamanho da amostra para estimar proporções

$$n = \pi(1-\pi)(\frac{z}{M})²$$

Onde M é a margem de erro desejada, Z é o escore-*z* para um intervalo de confiança com o nível de confiança desejado. Enquanto $\pi = 0.5$, normalmente.

## Tamanho da amostra para estimar médias

Nesse caso, precisa-se estimar o desvio padrão da população $\sigma$.

$$n = \sigma²(\frac{z}{M})²$$

Quanto maior a dispersão da distribuição populacional, maior o tamanho da amostra necessário para estar dentro de certa margem de erro.

*Precisão*: margem de erro.

*Confiança*: probabilidade de que o intervalo de confiança irá conter o parâmetro.

Quando a amostra é pequena, substituir escore-*z* por escore-*t*.

# Intervalos de confiança para médias e outros parâmetros

## Ineficiência da mediana amostral para dados normais.

Em distribuições normais, média e medianas são iguais, mas a mediana tem um erro padrão 25% maior, devido ao cálculo do erro padrão ser $ep = 1.25\sigma\sqrt{n}$. Por isso não é a mais recomendada.

Quando a distribuição populacional for altamente assimétrica, porém, a mediana populacional é um resumo mais útil.